### ISSUE TITLE
Dataset Refresh > wait until finished or return RefreshId ?

### ISSUE THREAD

**Issue by lgrosjean** [andrewvillazon/pbipy#24]
Dear maintainers,

First of all, thank you a lot for your job, your REST Api wrapper help me and my team a lot!

I'm using your package to send a RefreshRequest for some of my company Premium datasets. Dont you think it would help by improving the `Dataset.refresh` method by returning the `RequestId` generated after the `HTTP Post` instead of `None ?

Regarding the REST API documentation, it seems that the returned header contains the given `RequestId`: https://learn.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh#response

This request ID could be useful then to wait until the refresh is done to monitor the refresh of the dataset! I can help on this feature if you want.

Thank you for your time and you work again!

**Comment by andrewvillazon** [comment]
Glad to hear its helping! Thanks for the offer to contribute. I think the response has changed since the `Dataset.refresh` method was implemented, so this update would be welcome. Feel free to assign this one to yourself, fork, and add. The simplest update would be returning the `RequestId`, but if you also want to implement a refresh and wait feature go ahead, either is welcome

RE waiting for refresh. I think this should be implemented as a separate method, something like `refresh_and_wait()`, because `Dataset.refresh` wraps the endpoints that are designed to initiate a refresh and not wait. This would essentially be a convenience method. There's an existing `Dataset.refresh_details` method which can be used to check the status of the refresh. Let me know what you think.

**Comment by lgrosjean** [comment]
@andrewvillazon got it, I'll try to implement it on my side and let you know when I have a first version to share. I'll start with a simple one returning `requestId` and ,as well suggested, create a new method `refresh_and_wait` based on `refresh_details`

Keep in touch :)

**Comment by mertbakir** [comment]
It would be great if  refresh method can return the requestId, the api returns it: https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/refresh-dataset
