### ISSUE TITLE
Add authenticate if no app registered. 

### ISSUE THREAD

**Issue by WarrenGraham** [andrewvillazon/pbipy#40]
For multiple corporate enviroments there is no possibility for developers to register an app, for example due to company security policy. Thanks to msal library and provided by Microsoft app number developers can authenticate in their tenants using personal accont principal. After that work can progress 'as usual' in .pbi. Check this [repo](https://github.com/WarrenGraham/pyrestbi/blob/main/pyrestbi.py)- I can write in near future pull request for it.

**Comment by andrewvillazon** [comment]
Thanks for this. At the moment, the library deliberately avoids handling authentication. This is because there's different ways to authenticate depending on the user's Power BI setup and choice of authentication library. The only requirement the library has is that the user provides a Bearer Token. pbipy adds this to each request, in the same way you've done in your example. By choosing not to handle authentication, users have the flexibility to choose the right authentication method for their Power BI instance. Thanks for linking, as this is a useful example of authentication.
